Implement Fallback
koala-framework/kwf-weblate pull request #7
Opened 2022-03-09 13:53 UTC by qrakhen

Use kwf-weblate.fallback to apply fallback values to .po files.

2022-04-05 09:10 UTC, Schreglmann approved these changes

2022-04-05 09:11 UTC, Schreglmann commented
@qrakhen wart mim mergen bitte noch auf das Review vom @Ben-Ho

2022-04-06 11:11 UTC, Ben-Ho requested changes

2022-04-06 11:11 UTC, Ben-Ho commented on Kwf/Weblate/TrlParser.php
> +        $lines = explode("\n", $content);
@qrakhen bitte nicht selbst parsen. für sowas gibts einen poparser. irgendwo haben wir den schon im einsatz. wenns einen standard gibt, muss es auch einen parser dafür geben. po-files sind komplizierter als du glaubst ;-)

2022-04-06 11:11 UTC, Ben-Ho commented on Kwf/Weblate/TrlParser.php
> +        $lines = explode("\n", $content);
beim koala verwenden wir den "sepia/po-parser": "^4.2.1", https://github.com/koala-framework/koala-framework/blob/5.4/composer.json#L19

2022-04-06 11:16 UTC, Ben-Ho commented on Kwf/Weblate/DownloadTranslations.php
> +            file_put_contents($path, $trl->exportAsPo());
@qrakhen hier würde ich das ganze auch ohne erwähnung von po machen. im ganzen rest haben wir doch auch keine restriktion auf den datei-typ, oder?

2022-04-06 11:16 UTC, Ben-Ho commented on Kwf/Weblate/DownloadTranslations.php
> +            file_put_contents($path, $trl->exportAsPo());
also bitte so objekt-orientiert umsetzen, dass man ohne größere änderungen das file-format von po zb auf xml tauschen könnte. außer es würde jetzt extremen mehraufwand bedeuten...

2022-04-13 12:48 UTC, Ben-Ho approved these changes

2022-04-13 13:23 UTC, merged